version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_sequelize_api_db
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 8s
      timeout: 8s
      retries: 4

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "80:80"
    networks:
      - backend

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=node_sequelize_api_db
    networks:
      - backend

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
